site_name: LightningDB Docs
site_author: LightningDB Team
site_description: LightningDB is a DRAM / SSD optimized real-time in-memory DBMS.
site_url: https://mnms.github.io/docs
copyright: All right reserved, LightningDB Team.
google_analytics: ['UA-152587413-1', 'mnms.github.io/docs']

repo_name: source repository
repo_url: https://github.com/mnms/docs

nav:
  - Introduction:
    - Overview: index.md
    - Release Notes: release-note.md
  - Getting Started:
    - Prerequisite: prerequisite.md 
    - Installation: install-fbctl.md 
  - Tutorial:
    - Try out with Zeppelin: try-with-zeppelin.md 
  - Interface:
    - Command Line: command-line-interface.md
  - Operation:
    - Version update:  version-update.md   
  - Additional Resources:
    - Manual Installation: get-started-with-scratch.md

plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1
